name: ActionCrafter
main: com.actioncrafter.plugin.ActionCraftPlugin
version: 0.1
commands:
   event:
      description: this is actioncrafter.
      usage: /actioncrafter <event>
      permission: actioncrafter.event
      permission-message: You don't have <permission>   