name: ActionCrafter
main: com.actioncrafter.plugin.ActionCrafterPlugin
version: 0.3
commands:
   action:
      description: Send an action to ActionCrafter
      usage: /action <action_name> [<argument>=<value>|<argument>=<value>|...]
      permission: actioncrafter.action
      permission-message: You don't have <permission>   